import os
import logging
import shutil
from dv_flow.mgr import TaskDataResult, TaskRunCtxt, FileSet

_log = logging.getLogger("formal.vcf.Run")


def _generate_tcl(params, tcl_path, source_files):
    """Generate a VC Formal TCL control script from task parameters."""
    top = getattr(params, 'top', None) or 'top'
    clock = getattr(params, 'clock', 'clk') or 'clk'
    reset = getattr(params, 'reset', 'rst') or 'rst'
    reset_pol = getattr(params, 'reset_polarity', 'high') or 'high'
    reset_cycles = getattr(params, 'reset_cycles', 1) or 1
    depth = getattr(params, 'depth', 50) or 50
    proof_mode = getattr(params, 'proof_mode', 'all') or 'all'
    engine = getattr(params, 'engine', '') or ''
    timeout = getattr(params, 'timeout', 0) or 0

    try:
        depth = int(depth)
    except (TypeError, ValueError):
        depth = 50
    try:
        reset_cycles = int(reset_cycles)
    except (TypeError, ValueError):
        reset_cycles = 1
    try:
        timeout = int(timeout)
    except (TypeError, ValueError):
        timeout = 0

    flist_path = os.path.join(os.path.dirname(tcl_path), 'sources.f')
    with open(flist_path, 'w') as fl:
        for src in source_files:
            fl.write(f"{src}\n")

    active_val = '1' if reset_pol == 'high' else '0'
    inactive_val = '0' if reset_pol == 'high' else '1'

    with open(tcl_path, 'w') as fp:
        fp.write("# Auto-generated by dv-flow formal.vcf.Run\n\n")

        fp.write(f'read_file -top {top} -format sverilog -sva -vcs "-sverilog -f {flist_path}"\n\n')

        fp.write(f"create_clock {clock} -period 2\n\n")

        fp.write("# Reset is handled via SVA assume constraints\n")
        fp.write("sim_run -stable\n")
        fp.write("sim_save_reset\n\n")

        if engine:
            fp.write(f"set_fml_var fml_engine {engine}\n")
        fp.write(f"set_fml_var fml_max_proof_depth {depth}\n")
        fp.write("set_fml_var fml_effort high\n")
        if timeout > 0:
            fp.write(f"set_fml_var fml_max_time {timeout}s\n")
        fp.write("\n")

        if proof_mode == 'bmc':
            fp.write("check_fv -block\n")
        elif proof_mode == 'prove':
            fp.write("check_fv -block\n")
        elif proof_mode == 'all':
            fp.write("check_fv -block\n")
        else:
            fp.write("check_fv -block\n")

        fp.write("\nreport_fv -list\n")


def _parse_results(log_path):
    """Parse VC Formal log for proof results and return markers."""
    proven = 0
    falsified = 0
    inconclusive = 0
    covered = 0
    vacuous = 0

    if not os.path.isfile(log_path):
        return []

    with open(log_path, 'r') as fp:
        for line in fp:
            stripped = line.strip()
            if not stripped.startswith('['):
                continue
            if '] proven' in stripped or '] proven ' in stripped:
                proven += 1
            elif '] falsified' in stripped:
                falsified += 1
            elif '] inconclusive' in stripped:
                inconclusive += 1
            elif '] covered' in stripped:
                covered += 1
            elif '] vacuous' in stripped:
                vacuous += 1

    markers = []
    if proven > 0:
        markers.append({'severity': 'info', 'msg': f'{proven} properties PROVEN'})
    if covered > 0:
        markers.append({'severity': 'info', 'msg': f'{covered} cover points hit'})
    if vacuous > 0:
        markers.append({'severity': 'warning', 'msg': f'{vacuous} properties vacuous'})
    if inconclusive > 0:
        markers.append({'severity': 'warning', 'msg': f'{inconclusive} properties inconclusive (bounded)'})
    if falsified > 0:
        markers.append({'severity': 'error', 'msg': f'{falsified} properties FALSIFIED'})
    return markers


async def Run(ctxt: TaskRunCtxt, input) -> TaskDataResult:
    """Run VC Formal (vcf) proof session."""
    status = 0
    markers = []
    output = []

    source_files = []
    for fs in input.inputs:
        if getattr(fs, 'type', None) != 'std.FileSet':
            continue
        ftype = getattr(fs, 'filetype', None)
        if ftype in ('verilogSource', 'systemVerilogSource', 'formalLib'):
            for f in getattr(fs, 'files', []):
                path = os.path.join(fs.basedir, f)
                if path not in source_files:
                    source_files.append(path)

    top = getattr(input.params, 'top', None)
    if not top:
        markers.append({'severity': 'error', 'msg': 'Top module not specified'})
        return TaskDataResult(status=1, output=[], changed=False, markers=markers)

    if not source_files:
        markers.append({'severity': 'error', 'msg': 'No source files available for vcf'})
        return TaskDataResult(status=1, output=[], changed=False, markers=markers)

    custom_tcl = getattr(input.params, 'tcl_script', '') or ''
    if custom_tcl and os.path.isfile(custom_tcl):
        tcl_path = custom_tcl
    else:
        tcl_path = os.path.join(input.rundir, 'run_formal.tcl')
        _generate_tcl(input.params, tcl_path, source_files)

    cmd = ['vcf', '-batch', '-f', tcl_path]

    extra_args = getattr(input.params, 'args', []) or []
    cmd.extend(extra_args)

    _log.info("Running vcf: top=%s depth=%s proof_mode=%s",
              top, getattr(input.params, 'depth', 50),
              getattr(input.params, 'proof_mode', 'all'))
    status = await ctxt.exec(cmd, logfile="vcf.log")

    log_path = os.path.join(input.rundir, 'vcf.log')
    result_markers = _parse_results(log_path)
    markers.extend(result_markers)

    if status != 0 and not any(m.get('severity') == 'error' for m in markers):
        markers.append({'severity': 'error', 'msg': 'vcf exited with non-zero status; see vcf.log'})

    output.append(FileSet(
        src=input.name,
        filetype="formalRunDir",
        basedir=input.rundir,
    ))

    return TaskDataResult(
        status=status,
        output=output,
        changed=True,
        markers=markers,
    )
